export const SET_TICKET_OFFICE_DETAILS = 'SET_TICKET_OFFICE_DETAILS'
export const BOOK_TICKET = 'BOOK_TICKET'
export const SUCCESSFUL_TICKET_BOOKING ='SUCCESSFUL_TICKET_BOOKING'
export const SWITCH_TABS = 'SWITCH_TABS'
